# Generated by Django 2.0.7 on 2018-07-25 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('name', models.CharField(max_length=200)),
                ('amount', models.IntegerField()),
                ('comission', models.IntegerField()),
            ],
        ),
    ]
