# Generated by Django 2.0.7 on 2018-07-29 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20180728_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='total',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
