# Generated by Django 2.0.7 on 2018-07-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_transaction_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='amount',
            new_name='transfer',
        ),
    ]
